on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

name: Pages

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4

      - name: Install mc
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
        working-directory: /usr/local/bin

      - name: Configure mc
        run: |
          mc alias set s3 https://s3.amazonaws.com ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download
        run: |
          mc ls s3/keplerdemo --no-color | awk '{print $6}' | xargs -I{} mc get s3/keplerdemo/{} public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v3
